---
development:
  cloud_name: dp9k5sbd4
  api_key: '917397565664177'
  api_secret: r47NWHUWgxL6sKTADgod_oKJ230
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dp9k5sbd4
  api_key: '917397565664177'
  api_secret: r47NWHUWgxL6sKTADgod_oKJ230
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dp9k5sbd4
  api_key: '917397565664177'
  api_secret: r47NWHUWgxL6sKTADgod_oKJ230
  enhance_image_tag: true
  static_image_support: false
